package com.quanshi.ums.entity;

import java.util.Date;

public class EnvionmentVariables {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_envionment_variables.id
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_envionment_variables.env_key
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    private String envKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_envionment_variables.env_value
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    private String envValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_envionment_variables.create_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_envionment_variables.update_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_envionment_variables.id
     *
     * @return the value of tang_ums_envionment_variables.id
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_envionment_variables.id
     *
     * @param id the value for tang_ums_envionment_variables.id
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_envionment_variables.env_key
     *
     * @return the value of tang_ums_envionment_variables.env_key
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public String getEnvKey() {
        return envKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_envionment_variables.env_key
     *
     * @param envKey the value for tang_ums_envionment_variables.env_key
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public void setEnvKey(String envKey) {
        this.envKey = envKey == null ? null : envKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_envionment_variables.env_value
     *
     * @return the value of tang_ums_envionment_variables.env_value
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public String getEnvValue() {
        return envValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_envionment_variables.env_value
     *
     * @param envValue the value for tang_ums_envionment_variables.env_value
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public void setEnvValue(String envValue) {
        this.envValue = envValue == null ? null : envValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_envionment_variables.create_time
     *
     * @return the value of tang_ums_envionment_variables.create_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_envionment_variables.create_time
     *
     * @param createTime the value for tang_ums_envionment_variables.create_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_envionment_variables.update_time
     *
     * @return the value of tang_ums_envionment_variables.update_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_envionment_variables.update_time
     *
     * @param updateTime the value for tang_ums_envionment_variables.update_time
     *
     * @mbg.generated Mon Jun 12 17:59:48 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}