package com.quanshi.ums.entity;

import java.util.Date;

public class PushLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.action
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.user_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.site_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Long siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.display_name
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.status
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.times
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.create_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_push_log.update_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.id
     *
     * @return the value of ums_push_log.id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.id
     *
     * @param id the value for ums_push_log.id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.action
     *
     * @return the value of ums_push_log.action
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.action
     *
     * @param action the value for ums_push_log.action
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.user_id
     *
     * @return the value of ums_push_log.user_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.user_id
     *
     * @param userId the value for ums_push_log.user_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.site_id
     *
     * @return the value of ums_push_log.site_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.site_id
     *
     * @param siteId the value for ums_push_log.site_id
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.display_name
     *
     * @return the value of ums_push_log.display_name
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.display_name
     *
     * @param displayName the value for ums_push_log.display_name
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.status
     *
     * @return the value of ums_push_log.status
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.status
     *
     * @param status the value for ums_push_log.status
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.times
     *
     * @return the value of ums_push_log.times
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.times
     *
     * @param times the value for ums_push_log.times
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.create_time
     *
     * @return the value of ums_push_log.create_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.create_time
     *
     * @param createTime the value for ums_push_log.create_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_push_log.update_time
     *
     * @return the value of ums_push_log.update_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_push_log.update_time
     *
     * @param updateTime the value for ums_push_log.update_time
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}