package com.quanshi.ums.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.login_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.password
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.namepinyin
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String namepinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.namepinyin_full
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String namepinyinFull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.email
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.registertime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.lastlogintime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Date lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.last_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.userstatus
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Integer userstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.userforgetflag
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Boolean userforgetflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.country_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Long countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.timezone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String timezone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.mobile_number
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.organization_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.org_Name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.sex
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.register
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Boolean register;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.pass_type
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Integer passType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.first_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.middle_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String middleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.last_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.external_user_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String externalUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.external_user_addr
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String externalUserAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.external_config_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Long externalConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.position
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.display_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.office
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String office;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.office_phone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.icon_url
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.sign
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.role
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.password_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Date passwordUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user.password_level
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    private Integer passwordLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.id
     *
     * @return the value of tang_ums_user.id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.id
     *
     * @param id the value for tang_ums_user.id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.login_name
     *
     * @return the value of tang_ums_user.login_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.login_name
     *
     * @param loginName the value for tang_ums_user.login_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.password
     *
     * @return the value of tang_ums_user.password
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.password
     *
     * @param password the value for tang_ums_user.password
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.namepinyin
     *
     * @return the value of tang_ums_user.namepinyin
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getNamepinyin() {
        return namepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.namepinyin
     *
     * @param namepinyin the value for tang_ums_user.namepinyin
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setNamepinyin(String namepinyin) {
        this.namepinyin = namepinyin == null ? null : namepinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.namepinyin_full
     *
     * @return the value of tang_ums_user.namepinyin_full
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getNamepinyinFull() {
        return namepinyinFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.namepinyin_full
     *
     * @param namepinyinFull the value for tang_ums_user.namepinyin_full
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setNamepinyinFull(String namepinyinFull) {
        this.namepinyinFull = namepinyinFull == null ? null : namepinyinFull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.email
     *
     * @return the value of tang_ums_user.email
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.email
     *
     * @param email the value for tang_ums_user.email
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.registertime
     *
     * @return the value of tang_ums_user.registertime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.registertime
     *
     * @param registertime the value for tang_ums_user.registertime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.lastlogintime
     *
     * @return the value of tang_ums_user.lastlogintime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.lastlogintime
     *
     * @param lastlogintime the value for tang_ums_user.lastlogintime
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.last_update_time
     *
     * @return the value of tang_ums_user.last_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.last_update_time
     *
     * @param lastUpdateTime the value for tang_ums_user.last_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.userstatus
     *
     * @return the value of tang_ums_user.userstatus
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.userstatus
     *
     * @param userstatus the value for tang_ums_user.userstatus
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.userforgetflag
     *
     * @return the value of tang_ums_user.userforgetflag
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Boolean getUserforgetflag() {
        return userforgetflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.userforgetflag
     *
     * @param userforgetflag the value for tang_ums_user.userforgetflag
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setUserforgetflag(Boolean userforgetflag) {
        this.userforgetflag = userforgetflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.country_id
     *
     * @return the value of tang_ums_user.country_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.country_id
     *
     * @param countryId the value for tang_ums_user.country_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.timezone
     *
     * @return the value of tang_ums_user.timezone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.timezone
     *
     * @param timezone the value for tang_ums_user.timezone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.mobile_number
     *
     * @return the value of tang_ums_user.mobile_number
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.mobile_number
     *
     * @param mobileNumber the value for tang_ums_user.mobile_number
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.organization_id
     *
     * @return the value of tang_ums_user.organization_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.organization_id
     *
     * @param organizationId the value for tang_ums_user.organization_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.org_Name
     *
     * @return the value of tang_ums_user.org_Name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.org_Name
     *
     * @param orgName the value for tang_ums_user.org_Name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.sex
     *
     * @return the value of tang_ums_user.sex
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.sex
     *
     * @param sex the value for tang_ums_user.sex
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.register
     *
     * @return the value of tang_ums_user.register
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Boolean getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.register
     *
     * @param register the value for tang_ums_user.register
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setRegister(Boolean register) {
        this.register = register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.pass_type
     *
     * @return the value of tang_ums_user.pass_type
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Integer getPassType() {
        return passType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.pass_type
     *
     * @param passType the value for tang_ums_user.pass_type
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setPassType(Integer passType) {
        this.passType = passType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.first_name
     *
     * @return the value of tang_ums_user.first_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.first_name
     *
     * @param firstName the value for tang_ums_user.first_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.middle_name
     *
     * @return the value of tang_ums_user.middle_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.middle_name
     *
     * @param middleName the value for tang_ums_user.middle_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName == null ? null : middleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.last_name
     *
     * @return the value of tang_ums_user.last_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.last_name
     *
     * @param lastName the value for tang_ums_user.last_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.external_user_name
     *
     * @return the value of tang_ums_user.external_user_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getExternalUserName() {
        return externalUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.external_user_name
     *
     * @param externalUserName the value for tang_ums_user.external_user_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setExternalUserName(String externalUserName) {
        this.externalUserName = externalUserName == null ? null : externalUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.external_user_addr
     *
     * @return the value of tang_ums_user.external_user_addr
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getExternalUserAddr() {
        return externalUserAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.external_user_addr
     *
     * @param externalUserAddr the value for tang_ums_user.external_user_addr
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setExternalUserAddr(String externalUserAddr) {
        this.externalUserAddr = externalUserAddr == null ? null : externalUserAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.external_config_id
     *
     * @return the value of tang_ums_user.external_config_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Long getExternalConfigId() {
        return externalConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.external_config_id
     *
     * @param externalConfigId the value for tang_ums_user.external_config_id
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setExternalConfigId(Long externalConfigId) {
        this.externalConfigId = externalConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.position
     *
     * @return the value of tang_ums_user.position
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.position
     *
     * @param position the value for tang_ums_user.position
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.display_name
     *
     * @return the value of tang_ums_user.display_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.display_name
     *
     * @param displayName the value for tang_ums_user.display_name
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.office
     *
     * @return the value of tang_ums_user.office
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.office
     *
     * @param office the value for tang_ums_user.office
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setOffice(String office) {
        this.office = office == null ? null : office.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.office_phone
     *
     * @return the value of tang_ums_user.office_phone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.office_phone
     *
     * @param officePhone the value for tang_ums_user.office_phone
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.icon_url
     *
     * @return the value of tang_ums_user.icon_url
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.icon_url
     *
     * @param iconUrl the value for tang_ums_user.icon_url
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.sign
     *
     * @return the value of tang_ums_user.sign
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.sign
     *
     * @param sign the value for tang_ums_user.sign
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.role
     *
     * @return the value of tang_ums_user.role
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.role
     *
     * @param role the value for tang_ums_user.role
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.password_update_time
     *
     * @return the value of tang_ums_user.password_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Date getPasswordUpdateTime() {
        return passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.password_update_time
     *
     * @param passwordUpdateTime the value for tang_ums_user.password_update_time
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setPasswordUpdateTime(Date passwordUpdateTime) {
        this.passwordUpdateTime = passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user.password_level
     *
     * @return the value of tang_ums_user.password_level
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public Integer getPasswordLevel() {
        return passwordLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user.password_level
     *
     * @param passwordLevel the value for tang_ums_user.password_level
     *
     * @mbg.generated Mon Jun 12 16:13:31 CST 2017
     */
    public void setPasswordLevel(Integer passwordLevel) {
        this.passwordLevel = passwordLevel;
    }
}