package com.quanshi.ums.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public UserProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Integer value) {
            addCriterion("user_status =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Integer value) {
            addCriterion("user_status <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Integer value) {
            addCriterion("user_status >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_status >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Integer value) {
            addCriterion("user_status <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Integer value) {
            addCriterion("user_status <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Integer> values) {
            addCriterion("user_status in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Integer> values) {
            addCriterion("user_status not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Integer value1, Integer value2) {
            addCriterion("user_status between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("user_status not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andSitesIdIsNull() {
            addCriterion("sites_id is null");
            return (Criteria) this;
        }

        public Criteria andSitesIdIsNotNull() {
            addCriterion("sites_id is not null");
            return (Criteria) this;
        }

        public Criteria andSitesIdEqualTo(Long value) {
            addCriterion("sites_id =", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdNotEqualTo(Long value) {
            addCriterion("sites_id <>", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdGreaterThan(Long value) {
            addCriterion("sites_id >", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sites_id >=", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdLessThan(Long value) {
            addCriterion("sites_id <", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdLessThanOrEqualTo(Long value) {
            addCriterion("sites_id <=", value, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdIn(List<Long> values) {
            addCriterion("sites_id in", values, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdNotIn(List<Long> values) {
            addCriterion("sites_id not in", values, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdBetween(Long value1, Long value2) {
            addCriterion("sites_id between", value1, value2, "sitesId");
            return (Criteria) this;
        }

        public Criteria andSitesIdNotBetween(Long value1, Long value2) {
            addCriterion("sites_id not between", value1, value2, "sitesId");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeIsNull() {
            addCriterion("status_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeIsNotNull() {
            addCriterion("status_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeEqualTo(Date value) {
            addCriterion("status_modify_time =", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeNotEqualTo(Date value) {
            addCriterion("status_modify_time <>", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeGreaterThan(Date value) {
            addCriterion("status_modify_time >", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("status_modify_time >=", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeLessThan(Date value) {
            addCriterion("status_modify_time <", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("status_modify_time <=", value, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeIn(List<Date> values) {
            addCriterion("status_modify_time in", values, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeNotIn(List<Date> values) {
            addCriterion("status_modify_time not in", values, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeBetween(Date value1, Date value2) {
            addCriterion("status_modify_time between", value1, value2, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("status_modify_time not between", value1, value2, "statusModifyTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountIsNull() {
            addCriterion("is_host_account is null");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountIsNotNull() {
            addCriterion("is_host_account is not null");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountEqualTo(Byte value) {
            addCriterion("is_host_account =", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountNotEqualTo(Byte value) {
            addCriterion("is_host_account <>", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountGreaterThan(Byte value) {
            addCriterion("is_host_account >", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_host_account >=", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountLessThan(Byte value) {
            addCriterion("is_host_account <", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountLessThanOrEqualTo(Byte value) {
            addCriterion("is_host_account <=", value, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountIn(List<Byte> values) {
            addCriterion("is_host_account in", values, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountNotIn(List<Byte> values) {
            addCriterion("is_host_account not in", values, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountBetween(Byte value1, Byte value2) {
            addCriterion("is_host_account between", value1, value2, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andIsHostAccountNotBetween(Byte value1, Byte value2) {
            addCriterion("is_host_account not between", value1, value2, "isHostAccount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 12 16:34:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}