package com.quanshi.ums.entity;

import java.util.Date;

public class UserProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.user_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.product_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.user_status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.sites_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Long sitesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.status_modify_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Date statusModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.created_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.is_host_account
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Byte isHostAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tang_ums_user_product.status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.id
     *
     * @return the value of tang_ums_user_product.id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.id
     *
     * @param id the value for tang_ums_user_product.id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.user_id
     *
     * @return the value of tang_ums_user_product.user_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.user_id
     *
     * @param userId the value for tang_ums_user_product.user_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.product_id
     *
     * @return the value of tang_ums_user_product.product_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.product_id
     *
     * @param productId the value for tang_ums_user_product.product_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.user_status
     *
     * @return the value of tang_ums_user_product.user_status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.user_status
     *
     * @param userStatus the value for tang_ums_user_product.user_status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.sites_id
     *
     * @return the value of tang_ums_user_product.sites_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Long getSitesId() {
        return sitesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.sites_id
     *
     * @param sitesId the value for tang_ums_user_product.sites_id
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setSitesId(Long sitesId) {
        this.sitesId = sitesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.status_modify_time
     *
     * @return the value of tang_ums_user_product.status_modify_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Date getStatusModifyTime() {
        return statusModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.status_modify_time
     *
     * @param statusModifyTime the value for tang_ums_user_product.status_modify_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setStatusModifyTime(Date statusModifyTime) {
        this.statusModifyTime = statusModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.created_time
     *
     * @return the value of tang_ums_user_product.created_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.created_time
     *
     * @param createdTime the value for tang_ums_user_product.created_time
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.is_host_account
     *
     * @return the value of tang_ums_user_product.is_host_account
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Byte getIsHostAccount() {
        return isHostAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.is_host_account
     *
     * @param isHostAccount the value for tang_ums_user_product.is_host_account
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setIsHostAccount(Byte isHostAccount) {
        this.isHostAccount = isHostAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tang_ums_user_product.status
     *
     * @return the value of tang_ums_user_product.status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tang_ums_user_product.status
     *
     * @param status the value for tang_ums_user_product.status
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}