package com.quanshi.ums.dao;

import com.quanshi.ums.entity.PushLog;
import com.quanshi.ums.entity.PushLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    long countByExample(PushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int deleteByExample(PushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int insert(PushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int insertSelective(PushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    List<PushLog> selectByExample(PushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    PushLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") PushLog record, @Param("example") PushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int updateByExample(@Param("record") PushLog record, @Param("example") PushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int updateByPrimaryKeySelective(PushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_push_log
     *
     * @mbg.generated Tue Jun 13 10:54:55 CST 2017
     */
    int updateByPrimaryKey(PushLog record);
}