package com.quanshi.ums.dao;

import com.quanshi.ums.entity.UserProduct;
import com.quanshi.ums.entity.UserProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    long countByExample(UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int deleteByExample(UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int insert(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int insertSelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    List<UserProduct> selectByExample(UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    UserProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserProduct record, @Param("example") UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int updateByExample(@Param("record") UserProduct record, @Param("example") UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tang_ums_user_product
     *
     * @mbg.generated Mon Jun 12 16:34:38 CST 2017
     */
    int updateByPrimaryKey(UserProduct record);
}